namespace: online-boutique

replicaCount: 1


image:
  registry: docker.io/hishamatwa
  pullPolicy: IfNotPresent

imageTags:
  frontendservice: v1
  productcatalogservice: productcatalogservice-13
  currencyservice: currencyservice-11
  cartservice: cartservice-30
  paymentservice: paymentservice-6
  shippingservice: shippingservice-10
  emailservice: emailservice-5
  checkoutservice: checkoutservice-8
  recommendationservice: v1
  adservice: v1



redis:
  name: redis-cart
  replicaCount: 1
  service:
    type: ClusterIP
    port: 6379

frontend:
  service:
    type: NodePort
    port: 8080
    targetPort: 8080
    nodePort: 30080

backend:
  service:
    type: ClusterIP

shoppingAssistant:
  name: shoppingassistantservice
  port: 8080

services:
  adservice:
    port: 9555
  cartservice:
    port: 7070
  checkoutservice:
    port: 5050
  currencyservice:
    port: 7000
  emailservice:
    port: 8080
  paymentservice:
    port: 50051
  productcatalogservice:
    port: 3550
  recommendationservice:
    port: 8080
  shippingservice:
    port: 50051
