apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice
  namespace: {{ .Values.namespace | quote }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: cartservice
  template:
    metadata:
      labels:
        app: cartservice
    spec:
      containers:
        - name: cartservice
          image: "{{ .Values.image.registry }}/cartservice:{{ .Values.imageTags.cartservice }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: REDIS_ADDR
              value: "{{ .Values.redis.name }}:{{ .Values.redis.service.port }}"
---
apiVersion: v1
kind: Service
metadata:
  name: cartservice
  namespace: {{ .Values.namespace | quote }}
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    app: cartservice
  ports:
    - port: {{ .Values.services.cartservice.port }}
