apiVersion: apps/v1
kind: Deployment
metadata:
  name: productcatalogservice
  namespace: {{ .Values.namespace | quote }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: productcatalogservice
  template:
    metadata:
      labels:
        app: productcatalogservice
    spec:
      containers:
        - name: productcatalogservice
          image: "{{ .Values.image.registry }}/productcatalogservice:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
---
apiVersion: v1
kind: Service
metadata:
  name: productcatalogservice
  namespace: {{ .Values.namespace | quote }}
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    app: productcatalogservice
  ports:
    - port: {{ .Values.services.productcatalogservice.port }}

